### ISSUE TITLE
Refactoring: remove transfer reference to parent 

### ISSUE THREAD

**Issue by clehene** [Azure/azure-data-lake-store-python#188] opened 2017-08-10 01:13 UTC
### Description
It's an unnecessary coupling used to access an otherwise private field.
Instead `overwrite` should be a transfer parameter and `save()` should be passed as a reference like `merge` and `transfer`

**Comment by akharit** [comment] 2018-08-14 21:34
@clehene I know this is quite old but do you remember more information about this issue? I am having a hard time figuring what exactly is meant here, and if there is any context I am missing.

**Comment by clehene** [comment] 2018-08-16 22:07
@akharit I guess it's related to the design of some of the code which I must have encountered while fixing one of these https://github.com/Azure/azure-data-lake-store-python/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+clehene 

I'll take a look and see if I can point to the exact code if you can't find it.

**Comment by akharit** [comment] 2018-08-17 19:44
@clehene  Thanks. I'll look into your pull requests and see if I can identify what it might have been referring to.

**Comment by akharit** [comment] 2018-09-12 16:57
Looking at the code, it seems the issue is that for class ADLTransferClient, we are passing it a parent parameter, which is used to access the parent fields overwrite and save. 

The proposal is to remove the import of parent, and instead pass overwrite as a parameter to transfer() function, and pass save() function as another parameter. 

I am checking what code, if any this will break, and if there is some public api code that can break if I make the change, before proceeding.

**Comment by akharit** [comment] 2020-01-14 20:46
Closing this as not needed, unless the sdk needs refactoring.

**Closed by akharit** 2020-01-14 20:46 UTC
