### ISSUE TITLE
'upload' should not remove common prefix when uploading folders

### ISSUE THREAD

**Issue by nickraptis** [Azure/azure-data-lake-store-python#169] opened 2017-07-03 09:18 UTC
I'm trying to upload a tree of data using azure cli.
The folder structure looks something like "json/$project/$year/$month/$day/part_*.json"
I only have a couple of days data so, project,year,month are constant.

The command I issue is
az dls fs upload --source-path ./json --destination-path /json

My expectation was that the whole tree structure under json would be copied to DLS, as any other command like cp or rsync would do.

Instead, the $project/$year/$month part of the tree was omitted and I got a folder structure of  "json/$day/part_*.json"

It seems that the code computes a common prefix of all the files to be copied, and omits it.
For folder copying, this breaks expectations and should not be the case.

**Comment by begoldsm** [comment] 2017-07-06 18:28
@nickraptis thank you for the report and you are correct, this is not expected behavior. We will investigate this and fix it as soon as we can.

**Comment by begoldsm** [comment] 2017-07-06 22:23
@nickraptis can you also give the following info about your setup, to help our investigation and resolution:
1. Verison of the CLI/SDK that you are using (pip show azure-datalake-store)
2. OS type and version
3. Python version.

Thanks!

**Comment by nickraptis** [comment] 2017-07-07 15:07
$ az component list
...
  {
    "name": "dla",
    "version": "0.0.9"
  },
  {
    "name": "dls",
    "version": "0.0.9"
  },
...

(azure-cli) $ pip show azure-datalake-store
Name: azure-datalake-store
Version: 0.0.9
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /home/t_nikosr/.local/lib/azure-cli/lib/python3.4/site-packages
Requires: azure-nspkg, cffi, adal, msrest

OS : Linux Mint 17.3 (Ubuntu 14.04)
Python: Installed over Python 3.4.3 (system default is 2.7.6)

**Comment by begoldsm** [comment] 2017-07-07 16:40
Great, thank you for this additional information @nickraptis this will be very helpful for us to investigate why the common prefix logic is not properly working in this case. I will investigate and we should hopefully have this resolved soon.

**Comment by begoldsm** [comment] 2017-07-07 17:25
@nickraptis I am unable to reproduce this issue with the latest version of the azure-datalake-store package (0.0.13). Can you try updating that underlying package on your machine with: `pip install azure-datalake-store --upgrade`

If this resolves the issue then the next official release of the CLI will also resolve it, as it will automatically take a dependency on the latest version of the package. 

Thanks!

**Comment by nickraptis** [comment] 2017-07-10 12:08
I did upgrade what I could

from pip list:
azure-cli-dla (0.0.10)
azure-cli-dls (0.0.10)
azure-datalake-store (0.0.13)
azure-mgmt-datalake-analytics (0.1.6)
azure-mgmt-datalake-nspkg (2.0.0)
azure-mgmt-datalake-store (0.1.6)

The issue is still there, so I'll try and describe it a bit more:

The folder structure I'm trying to copy is:
worked
└── worked1
    └── worked2
        ├── worked3
        │   └── worked4
        │       └── worked5
        │           ├── also.txt
        │           └── worked.txt
        └── worked5
            ├── also.txt
            └── worked.txt

The command I'm using is
az dls fs upload --verbose --account <an account> --source-path ./worked --destination-path /

The result is this folder structure
/
├── worked3
│   └── worked4
│       └── worked5
│           ├── also.txt
│           └── worked.txt
└── worked5
    ├── also.txt
    └── worked.txt

It looks like the common prefix of the copied files gets thrown away, when it shouldn't, at least when trying to copy whole folders.

**Comment by begoldsm** [comment] 2017-07-10 21:40
@nickraptis aha, thank you for the repro folder structure! I was not creating the right structure when attempting it on my side. Based on this I am working on a potential fix now, as I have identified the code that is collapsing the common prefix. Thanks!

**Comment by begoldsm** [comment] 2017-07-11 20:48
@nickraptis this should be fixed with the latest release. Please install v0.0.14 and re-run your scenario and folder structure should now be maintained properly.

https://github.com/Azure/azure-data-lake-store-python/releases/tag/v0.0.14

**Closed by begoldsm** 2017-07-11 20:48 UTC
Labels: bug
