### ISSUE TITLE
multithread.ADLUploader hangs indefinitely

### ISSUE THREAD

**Issue by djtrumbe** [Azure/azure-data-lake-store-python#269] opened 2019-01-07 18:54 UTC
### Description

multithread.ADLUploader hanging when uploading many (~40) files simultaneously.

Some background:

 - We are processing many json files into tabular, parquet files.
 - This processing is done using ~40 worker threads, each thread processing a single file before grabbing another file off of the queue.
 - Each thread, pulls down the json file locally, iterates over the lines in the file, converts them to python dictionaries, flattens those dictionaries and adds them to a list.
 - Once this thread has processed all rows into a list of dictionaries, it creates a pandas dataframe with the data, then writes the data to a temporary, local parquet file, then uploads that file to an ADL.

The problem comes when there are thousands of very small files, so the processing of the files occurs quickly and we are quickly trying to upload many files simultaneously.  The process hangs indefinitely, producing no error nor returning at all.

Here are also a few code snippets to give you some understanding of how this all works:

import multiprocessing as mp
...
pool = mp.Pool(threads)
...
parse_results = pool.map(func=multi_process_file, iterable=process_info, chunksize=1)
...
to_adl_parquet(df, adl_file, adls, log_tag)
...
def to_adl_parquet(df, adl_file, adl_connection, log_tag='', timestamp_fix=False):
    log_tag = log_tag and '{} -'.format(log_tag) or log_tag
    temp_file = '{}/{}_{}'.format(TEMP_DIRECTORY, uuid.uuid1(), os.path.basename(adl_file))
    log('{}   writing temp file: {}'.format(log_tag, temp_file))
    if timestamp_fix:
        df.to_parquet(temp_file, coerce_timestamps='us', allow_truncated_timestamps=True)
    else:
        df.to_parquet(temp_file)
    file_size = os.path.getsize(temp_file)
    log('{}   uploading file:    {}  ({} bytes)'.format(log_tag, adl_file, file_size))
    multithread.ADLUploader(adl_connection, lpath=temp_file, rpath=adl_file, nthreads=1, overwrite=True)  ## THIS IS THE LINE THAT HANGS INDEFINITELY
    os.remove(temp_file)

---

### Reproduction Steps
This problem is difficult to consistently reproduce.  However, the more small files we are processing, the more likely this is to happen.

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)

Name: azure-datalake-store
Version: 0.0.39
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /home/etar/virtualenv/lib/python2.7/site-packages
Requires: futures, requests, cffi, azure-nspkg, adal, pathlib2
Required-by: azure

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  

Python 2.7.12

**OS Version:** What OS and version are you using?  

$ uname -a
Linux etar03-ubuntu-prd 4.15.0-1035-azure #36~16.04.1-Ubuntu SMP Fri Nov 30 15:25:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

bash

**Comment by akharit** [comment] 2019-01-07 19:50
@djtrumbe 

Just to confirm, when you say hang, does the execution continues till os.remove(temp_file) and there is a background thread in multithread.uploader that prevents the python process from exiting. Or does the python process not execute the os.remove(temp_file)? Also, is it consuming 100% CPU(so infinitte loop somewhere) or just idling(waiting for io). What is the way of generating adl_file names?

Are there adls logs that you can share when the process is hung? If not, can you enable logging and share them when the failure occurs? 

Also I see that you are using mp.Pool. Is to_adl_parquet launched by different processes or under the same python instance? Is there particular reason that you are launching with nthreads=1 ? And if possible, can you try removing that and checking if the error persists.

**Comment by djtrumbe** [comment] 2019-01-07 21:02
@akharit The execution never gets to deleting the file and so it's hanging somewhere in the ADLUploader call.

On your CPU question, we believe the thread goes idle.  However, we are not 100% sure on this.  We are trying to reproduce this again now and will report back if we can get back into this state.

On the file naming question, we are using a unique filename for each of the files we are writing into ADL.  While it's not 100% guaranteed uniqueness, this is very little chance of a file name collision.

On the logging question, how do I enable adls logging?  Of note, Dan C enabled diagnostics on the ADL location we are uploading to and provided those details to our Microsoft account rep as further information.

On your threading question, we are launching 40 real (not unaffected by the GIL) threads from the parent python process.  Each of those comes from the same python instance, but they are separate threads.  On the nthreads point, will this spin up more threads than the files that are being uploaded?  If so, we want to limit the threads to 1 to prevent the upload from locking up / taking down the server (over-utilizing the CPUs available on the box).

**Comment by akharit** [comment] 2019-01-07 21:30
@djtrumbe Thanks. That is helpful for me to investigate. 

Regarding logging. I'll also add this to the docs as well so people can use it easily.

```
#Top of the file.
import logging
adls_logger = logging.getLogger('azure.datalake.store')
adls_logger.addHandler(logging.FileHandler(filename="adls.log"))

.... OTHER CODE

adls_logger.setLevel(logging.DEBUG) # DEBUG produces a lot of output. 
SUSPECTED OFFENDING LINE
adls_logger.setLevel(logging.WARNING) # Set it back to WARNING to keep output under control.

```

Just fyi, this will produce a decent amount of output

Can you also mention my handle akharit to Microsoft account rep so it can be transferred easily to me on the backend side?

Regarding threading, the module uses threadpoolExecutor so it doesn't launch more threads than needed. It does chunk files if they are large so it can upload them in parallel. The chunk size by default is 268 Mb.  So for a file under 268 Mb it should be one thread.

**Comment by djtrumbe** [comment] 2019-01-28 20:57
Hi @akharit - Apologies for the delayed response.  We have been trying to reproduce the issue while continuing to add debug information to get to the bottom of where this is hanging.  We now have very specific information on what's going on.

My colleague has helped to produce a stack trace within the running, but hung software (below).  This was generated from the "multiprocessing" thread that was hung, never returning from its processing.  Here is the code from json_to_parquet.py around line 185, which is where the problem first originates:

    with adls_prod.open(json_file, 'rb') as f:
        start = datetime.now()
        for line in f:

And here is the instantiation of adls_prod:

adls_prod = core.AzureDLFileSystem(token, store_name=util.ADL_PROD_LOCATION)

As you can see, this is hung in some SSL code waiting for a read to happen.

Can you please take a look?  Also, please reach out if you have further questions or need more clarification.

Thanks!



(gdb) py-bt
Traceback (most recent call first):
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/urllib3/response.py", line 615, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/urllib3/response.py", line 669, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/etar/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/lib.py", line 476, in __call_once
    return func(url, params=params, headers=req_headers, data=data, stream=stream)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/lib.py", line 416, in call
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/core.py", line 1062, in _fetch_range
    'OPEN', path, offset=start, length=end-start, read='true', stream=stream, retry_policy=retry_policy, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/core.py", line 1070, in _fetch_range_with_retry
    return _fetch_range(rest, path, start, end, stream=False, retry_policy=retry_policy, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/core.py", line 820, in _fetch
    self.azure.azure, self.path.as_posix(), self.start, self.end, filesessionid=self.filesessionid)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/core.py", line 844, in _read_blocksize
    self._fetch(offset, offset + self.blocksize)
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/core.py", line 787, in readline
    self._read_blocksize()
  File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/core.py", line 802, in __next__
    out = self.readline()
  File "/home/etar/etar_cloud/transform/json_to_parquet.py", line 185, in process_file
    for line in f:
  File "/home/etar/etar_cloud/transform/json_to_parquet.py", line 127, in multi_process_file
    parse_result = process_file(json_file, file_position, total_file_count, file_size, threaded=True)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/home/etar/etar_cloud/transform/json_to_parquet.py", line 364, in main
    pool = mp.Pool(threads)
  File "/home/etar/etar_cloud/transform/json_to_parquet.py", line 453, in <module>
    main(args.start_date, args.end_date, args.file_tag, args.host_tag, args.adl_file, args.reprocess, args.threads)

**Comment by akharit** [comment] 2019-01-28 21:14
@djtrumbe Thanks for reaching back.

Just to confirm, as I see from the stack trace the bug is when we are reading i.e downloading a file from adls, and not when uploading a file?

Is this reproducible from a single thread for that particular file? Or does it only happen when you are trying it using multitthreading?

As I mentioned before, it would be very helpful for me if I can get adls specific logs, as that allows me to query our servers and see exactly what is going on in the backend for that file. 

I mentioned the instructions before on how to generate the required logs. 

If you are not comfortable posting them here, you can also email them to me at akharit@microsoft.com.

**Comment by djtrumbe** [comment] 2019-01-28 22:31
Hi @akharit 

I'm not 100% sure that it only happens on reads.  However, the situation we caught was definitely around reading / downloading.  Now that we have a better workflow for pulling this information and we are causing these hangs in the processing we are looking to do anyway, we should be able to validate this the next time it happens (possibly even tomorrow).

We have another process that is hanging as well that we have yet to catch the issue with the amount of information we have here.  That process is also using multiprocessing, but we haven't confirmed where the hang is happening yet.  We have added the same level of information to this process to be able to pull a stack trace on the hung process the next time it happens.

On the debug logging, we turned this on temporarily to try to get more information.  We will provide this info, along with the stack trace of the hung threads the next time this happens.

**Comment by akharit** [comment] 2019-02-04 19:53
Closing. Have add a break on zero byte reads, though it is a server error, rather than python module error.

**Comment by akharit** [comment] 2019-02-04 19:54
Wrongly closed. Still not sure on root cause. But have added some possible mitigations like moving check_token to retry and exposing timeout for uploader/downloader

**Comment by djtrumbe** [comment] 2019-02-15 21:20
Hi @akharit 

Per our offline discussions, we believe this was a routing issue on our side, fixed by a UDR.  Since adding a UDR for this, we have not seen this issue recur.  Feel free to close out this issue now.

Thanks again for all of your help here!

**Closed** 2019-02-26 18:38 UTC
