### ISSUE TITLE
Feature Request: Better logic for folder upload/download when overwrite=false

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-data-lake-store-python#145] opened 2017-02-07 21:25 UTC
Currently it throws an exception.  This is painful.

Check this code, just to be sure, but I upload an entire folder.  Sometimes things go wrong and upload is interrupted.  So I move the already done files to another folder and keep uploading the source folder.

Getting remote file list appears to not necessarily match the local file list.

SomeFunctions
`#%%
def GetADLSManager():
    credentials = UserPassCredentials(user, password, tenant = tenant)
    return DataLakeStoreAccountManagementClient(credentials, subscriptionId)

def GetADLFileManager():
    token = lib.auth(tenant_id = tenant, username = user, password = password)
    return core.AzureDLFileSystem(token, store_name=adlsAccountName)

#%%
def Upload(source, destination, threads = 4, overwrite = False, filemanager = None):
    if(filemanager == None):
        filemanager = GetADLFileManager()
    ADLUploader(filemanager, destination, source, nthreads = threads, overwrite = overwrite)`

`source = 'STUFF'
dest = 'STUFF'
Upload(source, dest, threads = 1)`

`import pandas as pd
man = GetADLFileManager()
rData = man.ls('REMOTE')
rData = pd.Series(rData)
remoteFiles = rData.str.rsplit('/', expand = True, n = 1)[1]
localFiles = GetLocalFiles(source)
deltaFiles = localFiles[np.invert(localFiles.isin(remoteFiles))]
#localFiles[[False if file in remoteFiles else True for file in localFiles]]
doneFiles = localFiles[localFiles.isin(remoteFiles)]

#%%
for file in doneFiles:
    filepath = os.path.join(source, file)
    shutil.move(filepath, os.path.join('LOCAL_DONE', file))`

After moving the folde,r try uploading again with the command: 

`source = 'STUFF'
dest = 'STUFF'
Upload(source, dest, threads = 1)`

**Comment by begoldsm** [comment] 2017-02-08 19:08
@drcrook1 what version of the package are you using (should be at least 0.0.3)?
What errors are you getting on upload that is resulting in the interruption?
When you do your move and re-upload what files are missing?

We have an enhancement to support resume (#124 ), which would help with your interrupt scenario, but I would first like to understand what is causing the interrupt to see if we can fix that root cause first.

**Comment by drcrook1** [comment] 2017-02-09 15:41
The interrupt was caused by me stopping and starting it again due to super slow speeds.  I adjusted some code and tried to resume again.  The biggest issue for me is really around performance, but this was an easier and more concrete issue to report.

**Comment by begoldsm** [comment] 2017-02-09 19:18
Based on the code snippets above, your poor performance is expected. You are explicitly setting the parallelism of the operation to 1, which is the equivalent of a sequential upload, which will upload each file in sequence, one 4mb chunk at a time.

In most cases, you should see fairly good performance with default thread count, however if the machine you are doing the upload from does not have a large number of cores, you may want to try explicitly setting the nthreads parameter somewhere between 30 - 64, based on the capabilities of your hardware.

**Comment by begoldsm** [comment] 2017-03-10 19:24
@drcrook1 I am turning this into a feature request, as we now have a couple of issues regarding the current "heavy handed" approach to folder upload and download and overwrite. Our team will prioritize this and use this issue to track our progress and making folder transfer experiences more intuitive and usable.

**Comment by drcrook1** [comment] 2017-04-04 23:08
Any updates on this one?  Its causing pain in our teams.

**Comment by begoldsm** [comment] 2017-06-01 22:15
@drcrook1 there is a fix for this in the latest version of the SDK. Now, if a folder already exists we will upload the contents to that folder provided that they have no collisions with leaves (files) in that folder (this includes nested folders). If there are files that it would collide with, an exception will be thrown that gives the full list of files that it will collide with so that you can make a decision about using the overwrite flag or re-running upload for just the conflicted files.

**Closed by begoldsm** 2017-06-01 22:15 UTC
Labels: enhancement
