### ISSUE TITLE
Specify Read/Connect Timeout in AzureDLFileSystem

### ISSUE THREAD

**Issue by skadyan** [Azure/azure-data-lake-store-python#287] opened 2019-06-07 07:20 UTC
### Description
It appears that there is no option of specifying the read/write timeout . Due to some network glitches, call to API like AzureDLFileSystem#open() or AzureDLFileSystem#ls() never return. Also infinite timeout (which seems default underlying in requests library), retry logic also not getting kicked in.  
As a result , our application script get hangs. 

Do we have any way to specify read/connect timeout per request or per ?
---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here:
Python 3.6.1
requests==2.19.1
requests-kerberos==0.12.0
azure-datalake-store==0.0.22

**OS Version:** What OS and version are you using?  
Answer here: Linux

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by sachinsbigdata** [comment] 2019-06-10 04:25
Hi,

We have not heard of this issue wiht other customers. Can you please clarify how often you are seeing this? Also can you share where your application script is running? Is your application running in an Azure region different from where ADLS Gen1 account is?

Thanks.

**Comment by dcieslak19973** [comment] 2019-06-19 20:14
I am a different customer and we began observing the same behavior described by @skadyan around the same time (roughly 2 weeks ago now).

Relevant info:
Python 3.6.5
azure-datalake-store==0.0.45
OS: CentOS 7

Issue is that we're getting stuck on AzureDLFileSystem.open()

We've raised a support ticket with Microsoft as of yesterday as we were unable to mitigate the problem on our own. We have worked previously with @akharit on similar issues, where we needed a timeout added to the ADLUpload / Download.

**Comment by akharit** [comment] 2019-06-19 20:28
@dcieslak19973 timeout in download/upload is needed since they are operations that do take a long time to complete. open() should be a very short operation and ideally not need timeout. Hanging here suggests that there is some other root cause. Can you enable logging and get back to me with that?

    import logging
    adls_logger = logging.getLogger('azure.datalake.store')
    adls_logger.addHandler(logging.FileHandler(filename="adls.log"))
    .... OTHER CODE
    adls_logger.setLevel(logging.DEBUG) # DEBUG produces a lot of output. 
    OPEN CALL THAT IS HANGING HERE.
    adls_logger.setLevel(logging.WARNING) # Set it back to WARNING to keep output under control.

Is this after update to 0.0.45? I refactored open method in that to reduce number of calls to server for opening a file, but ideally the behavior shouldn't have changed.

**Comment by dcieslak19973** [comment] 2019-06-20 15:30
Yes, we have been running 0.0.45 and experiencing this issue. We have changed our logging and will post a sample when the error re-occurs.

Are there any current (as of 20-JUN-2019) problems with the Azure Data Lake service itself?

**Comment by akharit** [comment] 2019-06-20 20:23
> Yes, we have been running 0.0.45 and experiencing this issue. We have changed our logging and will post a sample when the error re-occurs.
The original issue has been filed on 0.0.22 so I am not sure if this is caused by my changes in 0.0.44 to 0.0.45, but I am still looking. 

> Are there any current (as of 20-JUN-2019) problems with the Azure Data Lake service itself?
None that I know of.

Can you mention here, or in the support ticket some samples of file name, and approximate time when the request failed? Is it only for particular files or random?

To unblock yourself, you can use something like https://github.com/kata198/func_timeout, till we figure this out.

**Comment by akharit** [comment] 2019-06-28 03:26
Add per request retry. Quite a few calls do make more than one request(like ls), so this can't be used as an explicit timeout for each api, but should stop the problem of requests library causing an infinite loop waiting for data. Closing.

**Closed by akharit** 2019-06-28 03:26 UTC

**Comment by skadyan** [comment] 2019-08-21 16:14
@akharit thanks for fix. In order to specify connect and read timeout respecively, can we specify a tuple (float, float) value for newly introduced parameter `per_call_timeout_seconds`? I believe it should work, as this value is being passed to [underlying HTTPAdapter](https://github.com/psf/requests/blob/b6b90f4d9bd447c8ae41cd31d75547fdafc25159/requests/adapters.py#L67). Probably worth to mentioned in API's documentation.
