### ISSUE TITLE
AccessControlException after file upload

### ISSUE THREAD

**Issue by avaranovich** [Azure/azure-data-lake-store-python#95] opened 2016-10-06 07:53 UTC
I am trying to upload the content of the local file into a DataLake store, with the following simple snippet:

```
token = lib.auth(tenant_id='782633d2-40ee-4e13-a016-xxxx', client_id='6a706405-9ef2-440c-9585-xxxxx', client_secret='yyyy=')
adl = AzureDLFileSystem(store_name='mystore', token=token)

adl.put('updates/update.xml', update.xm)
```

I can see the file is a data explorer, with a non-zero size, however, once I click on the file, I get

```
 Error
AccessControlException
Message
FsOpenStream failed with error 0x83090aa2 (Either the resource does not exist or the current user is not authorized to perform the requested operation).

 [58c2c59a-1a6d-42da-aaff-9f9bde8216be] failed with error 0x83090aa2 (Either the resource does not exist or the current user is not authorized to perform the requested operation).

 [58c2c59a-1a6d-42da-aaff-9f9bde8216be][2016-10-06T00:44:11.1559029-07:00]
```

I can oly delete the file from web browser. My user is the owner of the root datalake store folder.

**Comment by begoldsm** [comment] 2016-10-06 17:05
@avaranovich did the folder "updates" exist prior to the put? Can you also confirm the permissions that are on the folder and file? The inherited permissions may be reduced to just --x instead of rwx in this case. In the meantime I will try and repro on my side to see what is going on.

**Comment by avaranovich** [comment] 2016-10-07 09:45
Let me clarify the set up: I am uploading the file using service principal acocunt (the app is registered in Azure AD, and the permissions are given) and accessing the file with my personal user account via Azure portal. See how the permissions are set up

[Permissions](http://take.ms/NXHjO)

AzureDataLakePowerBI is the service account used in my python code, and above is my user account.

**Comment by begoldsm** [comment] 2016-10-10 17:26
Thank you for the clarification @avaranovich. I will follow up with our ACL team to understand what could be causing this interaction. Out of curiosity, can you explicitly give your user account permissions on the file using the service principal in python and will that allow you to then access the file as you would expect?

**Comment by begoldsm** [comment] 2017-01-30 20:27
@avaranovich is this still an issue? I confirmed with our ACL team that the scenario you described should be resolved with our introduction of the "super user" feature. Please let me know, otherwise I will consider this issue to be closed.

Thanks!
Ben

**Comment by avaranovich** [comment] 2017-02-01 13:43
@begoldsm what is the "super user" feature?

**Comment by begoldsm** [comment] 2017-02-01 19:23
@avaranovich it is functionality built into the service now where any owner of the account itself will also have full RWX access on the full filesystem within the account. Basically, all account owners are superusers. Regardless of that feature, are you still able to reproduce your issue?

**Comment by begoldsm** [comment] 2017-03-10 19:29
@avaranovich friendly ping here. Are you still experiencing this issue? I will be closing out this issue on Monday (03/11/2017) if you are not or I don't hear back as part of issue clean up in this repository.

**Comment by avaranovich** [comment] 2017-03-13 10:21
Yes, I still can reproduce the issues. In fact I can also reproduce it under the followin set up: upload the file using the user (not app principal), and then try to access the file with the user from _different_ Azure AD, who is also an owner of the ADL Store.

**Comment by begoldsm** [comment] 2017-03-24 18:40
@avaranovich the second scenario is not actually supported. The other user must be a member of the same AAD as the data lake store account in order to have any access. So you would need to log in as that user using the tenant ID of the AAD tenant the Data Lake Store account is in. 

For ADLS, I recommend going through the following steps with your account through the portal first to make sure they work:
1. identify the user/tenant combination of an owner of the ADLS account
2. verify that, as the owner you can access any file/folder that was created by a different user (this is the "super user" feature, where members of the account owner group will always have full access to all data in the account). If you still get access denied errors, then the user you are logged in with may not actually be a member of the owner group for the resource. Try going back to the IAM blade in the portal for the ADLS account and adding this user to the owner group

Now, with your service principal, or a different account:
3. login through python using the same tenant ID as the one your ADLS account was created under. This is very important, since cross tenant auth is not supported for ADLS.
4. Create your file/folder as the service principal/other user. If this fails with permissions issues, make sure to give this account/service principal write and execute permissions at a minimum on the folder structure leading to where the user wants to write to.

Now that the service principal (or other user) created a file, you can go back to the portal as your owner account and try to access it. If this still fails, double check again that the owner is logged in to the right AAD tenant and that it is a member of the owner group. If all of this is true and you are still reproducing this issue please give me both the script and the repro steps (without your sensitive information) and I will investigate with our security and access team to help unblock you.

**Comment by avaranovich** [comment] 2017-04-28 13:05
I solved the issue of multiple AADs by **chmod '0777'** of every uploaded file. This way the users from the other AADs granted permissions via portal can read the file. It might not be a supported scenario (even I am still not sure how such chmod related to the ACL assigned via portal), but it works.

**Comment by begoldsm** [comment] 2017-06-01 22:13
@avaranovich I am glad to hear you figured this out! If you feel that this behavior is not ideal or as expected, I definitely recommend giving this feedback at http://aka.ms/adlfeedback. Since you have resolved this, I am closing out this issue now.

**Closed by begoldsm** 2017-06-01 22:13 UTC
