### ISSUE TITLE
Missing azure/__init__.py in wheel causes import errors

### ISSUE THREAD

**Issue by macoun** [Azure/azure-data-lake-store-python#272] opened 2019-01-30 09:50 UTC
Hi,

maybe I'm missing something here. So, my apologies if this issue makes no sense. The problem is that the umbrella package `azure` (I guess this is an umbrella package) is not recognised without an appropriate `__init__.py` file.

This is what I get

```
    from azure.datalake.store import core, lib, multithread
ImportError: No module named datalake.store
``` 

I checked the release package and couldn't find `azure/__init__.py`. I'm not sure if this is an intended behaviour. 

```
unzip -t ~/Downloads/azure_datalake_store-0.0.40-py2.py3-none-any.whl
Archive:  /Users/ayaz/Downloads/azure_datalake_store-0.0.40-py2.py3-none-any.whl
    testing: azure/datalake/__init__.py   OK
    testing: azure/datalake/store/__init__.py   OK
    testing: azure/datalake/store/core.py   OK
    testing: azure/datalake/store/enums.py   OK
    testing: azure/datalake/store/exceptions.py   OK
    testing: azure/datalake/store/lib.py   OK
    testing: azure/datalake/store/multiprocessor.py   OK
    testing: azure/datalake/store/multithread.py   OK
    testing: azure/datalake/store/retry.py   OK
    testing: azure/datalake/store/transfer.py   OK
    testing: azure/datalake/store/utils.py   OK
    testing: samples/__init__.py      OK
    testing: samples/benchmarks.py    OK
    testing: samples/cli.py           OK
    testing: azure_datalake_store-0.0.40.dist-info/METADATA   OK
    testing: azure_datalake_store-0.0.40.dist-info/WHEEL   OK
    testing: azure_datalake_store-0.0.40.dist-info/top_level.txt   OK
    testing: azure_datalake_store-0.0.40.dist-info/RECORD   OK
No errors detected in compressed data of /Users/ayaz/Downloads/azure_datalake_store-0.0.40-py2.py3-none-any.whl.

```
---

### Reproduction Steps
```
conda create --name env python=2.7
source activate env
pip install azure-datalake-store
python -m azure.datalake.store
/home/ayaz/.conda/envs/delme/bin/python: No module named datalake

```
### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
```
$ pip show azure-datalake-store
Name: azure-datalake-store
Version: 0.0.40
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /home/ayaz/.conda/envs/delme/lib/python2.7/site-packages/azure_datalake_store-0.0.40-py2.7.egg
Requires: cffi, adal, requests, pathlib2, futures, azure-nspkg

```
**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  

ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, not stripped

**OS Version:** What OS and version are you using?  
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
```
$ echo $SHELL
/bin/bash
```

**Comment by macoun** [comment] 2019-01-30 19:54
azure-nspkg is also installed but they both are installed in separate folders within site-packages.

**Comment by akharit** [comment] 2019-01-30 19:57
Can you mention the path structure for azure-nspkg and azure-datalake-store package in site-packages? What folder is azure-nspkg installed in?

**Comment by macoun** [comment] 2019-01-31 08:38
Sorry for the delay. Here is an output of `ls` in site-packages.

```
$ls azure_*/*
azure_datalake_store-0.0.40-py2.7.egg/EGG-INFO:
PKG-INFO  SOURCES.txt  dependency_links.txt  not-zip-safe  requires.txt  top_level.txt

azure_datalake_store-0.0.40-py2.7.egg/azure:
datalake

azure_datalake_store-0.0.40-py2.7.egg/samples:
__init__.py  __init__.pyc  benchmarks.py  benchmarks.pyc  cli.py  cli.pyc

azure_nspkg-3.0.2-py2.7.egg/EGG-INFO:
DESCRIPTION.rst  PKG-INFO  RECORD  WHEEL  metadata.json  top_level.txt

azure_nspkg-3.0.2-py2.7.egg/azure:
__init__.py  __init__.pyc

```

**Comment by akharit** [comment] 2019-01-31 23:52
I tried the steps, though on a windows system, and I do see an azure, datalake, and store folders having the ```__init__.py``` file. 

```
conda create --name env python=2.7
source activate env
pip install azure-datalake-store
python -m azure.datalake.store
python.exe: No module named azure.datalake.store.__main__; 'azure.datalake.store' is a package and cannot be directly executed.
``` 
This just means that we don't have a main module for datalake store package. 
Running a python shell and 
```import azure.datalake.store ```
works for me.

Can I get the conda version installed?

Also, if possible can you list the contents of azure directory under site-packages. The command 
```$  find ./site-packages/azure -ls```

should work to get that info, if you don't have tree command installed.

**Comment by akharit** [comment] 2019-01-31 23:55
Also, can you please verify that pip install azure-datalake-store==0.0.39 is working?

**Comment by macoun** [comment] 2019-02-04 10:12
It works on my macOS, too. I can confirm that it works for Windows as well. Installing 0.0.39 works like a charm on my Mac. However, even 0.0.39 is missing __init__.py on RedHat 7.

**Comment by akharit** [comment] 2019-02-04 19:52
@lmazuel Any idea what is going on here? This seems like an azure-nspkg issue rather than adls issue since azure-nspkg does get installed, but doesn't create the init file. I am not sure why it is happening only on red hat though.

**Comment by lmazuel** [comment] 2019-02-06 00:43
So to summarize if I get it correctly:
- @akharit you cannot reproduce it on recent conda
- @macoun on your **_conda version_** 0.0.40 is broken, but 0.0.39 doesn't

I see in your logs @macoun that for some reason pip installed datalake as eggs, which is highly deprecated (and likely the root cause of the issue). Could you give the version of pip installed?

**Comment by toshetah** [comment] 2019-02-19 09:08
I would try to uninstall and reinstall azure-nspkg.
@macoun, did you try that?

**Comment by akharit** [comment] 2019-02-28 19:12
@macoun  Has this been resolved?

**Comment by akharit** [comment] 2019-03-11 23:56
Closing.

**Closed by akharit** 2019-03-11 23:56 UTC
